pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - status-success=ci/circleci
      - status-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merge from Dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
      - status-success=ci/circleci
      - status-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: merge
        strict: true
