pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
     - "#approved-reviews-by>=1"
#     - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merge from Dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
        strict: true
